# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Switchboard < Formula
  desc "TBD
"
  homepage "https://github.com/Cian911/switchboard"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Cian911/switchboard/releases/download/v1.0.0/switchboard_1.0.0_Darwin_arm64.tar.gz"
      sha256 "5c8c96cc4a810490d63b80799d91da232f87bc34da16af12326c839f5e3a8fcb"

      def install
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Cian911/switchboard/releases/download/v1.0.0/switchboard_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "53d77120d69a8c3761cc61296b0399d0ae7a65b4b9c198776169f6fda50439c6"

      def install
        bin.install "switchboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Cian911/switchboard/releases/download/v1.0.0/switchboard_1.0.0_Linux_x86_64.tar.gz"
      sha256 "cf671ec444bbd29eaed33112d53f2def6e878a930f61d8f1226c827432848546"

      def install
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cian911/switchboard/releases/download/v1.0.0/switchboard_1.0.0_Linux_arm64.tar.gz"
      sha256 "465cafac101fcc9ea57e8660cfc2123d6ac124c4a50756b909edc92af60ecb6e"

      def install
        bin.install "switchboard"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Cian911/switchboard/releases/download/v1.0.0/switchboard_1.0.0_Linux_armv6.tar.gz"
      sha256 "5102d1f706f67733a0bc719d77a519bf4218d1b4506301f561eaccc29c90a047"

      def install
        bin.install "switchboard"
      end
    end
  end
end
